== Início das Atividades

Bom dia a todos, sejam bem vindos ao curso *Processo Ágil de Produção de Livros* que *terá inicio* em:

Data:: *SEGUNDA-FEIRA, 11 de Novembro*.
Horário:: *TARDE, 14:15 às 17:45*.
Local:: Laboratório de capacitação da UFPB Virtual (ao lado da reitoria, prédio laranja).

=== Contato

|====
| Eduardo | 8108-1977| eduardo.ufpb@gmail.com
|====

=== Recomendações

Tragam seus notebooks:: Será necessário instalação de aplicativos para produção dos livros.
Conta de usuáiro no github:: Faça uma conta de usuário no https://github.com[github] antes de começar a aula, 
pois se deixar para última hora talvez não conseguirá criar uma conta.

NOTE: Devido a uma nova demanda da UFPB Virtual, o horário foi do nosso curso foi alterado 
de *Manhã* para *Tarde*, atualizem suas agendas.

=== Webconferência

Enquanto o curso não inicia, vocês podem assistir à webconferência
realizada anteriormente: http://webconf2.rnp.br/p5ygdcz3cp4/


NOTE: Já foi solicitado ao suporte o cadastro de vocês na sala de aula virtual.
